### ISSUE TITLE
Tyk Integration plugin kills the response

### ISSUE THREAD

**Issue by sedkis** [apiclarity/apiclarity#70]
Using `httpbin.org` upstream with the sample included Tyk integration plugin, the integration works and the telemetry data flows into APIClarity, but the API Response being returned to the client is killed:

```
$ curl localhost:8080/httpbin/json
curl: (18) transfer closed with 429 bytes remaining to read
```

**Comment by fishkerez** [comment]
Hi @sedkis 
Thank you for taking your time and open this issues!

Can you please elaborate a bit more on how to reproduce the httpbin issue?
Specifically how is the httpbin and Tyk are installed/deployed on your cluster

**Comment by sedkis** [comment]
> Hi @sedkis Thank you for taking your time and open this issues!
> 
> Can you please elaborate a bit more on how to reproduce the httpbin issue? Specifically how is the httpbin and Tyk are installed/deployed on your cluster

Of course.

I don't think the issue is httpbin, I think the issue is in the plugin. 
I used 3 different upstreams, all of which were outside the cluster, sitting on public endpoints
- httpbin.org
- petstore.swagger.io
- jsonplaceholder.typicode.com

And the result was always the same, which is the telemetry data was sent to APIClarity, but no response was received by the client.  Are you able to see a response in the client when using the patched Tyk README deployment steps?

**Comment by fishkerez** [comment]
It does reproduce you are correct.
The reason is that we use io.Read on the response body in the plugin in order to send it in the telemetry.
Since the response body is a Reader, it is basically a stream, so once you read it, it will not be read again (in the response to the user).
I will figure out how to read the response body without clearing the stream and will push a fix.
